=== positive-real-function/XML/code/TD_DTD_schema/gare.dtd
<!ELEMENT gare (train+,usager+)>
<!ELEMENT train (voiture+,commentaire*)>
<!ATTLIST train 
        numero ID #REQUIRED 
        type CDATA #IMPLIED>
<!ELEMENT voiture (resa*,bar*)>
<!ATTLIST voiture numero CDATA #REQUIRED>
<!ELEMENT resa EMPTY>
<!ATTLIST resa 
        numero ID #REQUIRED 
        id IDREF #REQUIRED>
<!ELEMENT bar EMPTY>
<!ATTLIST bar service CDATA #REQUIRED>
<!ELEMENT commentaire (#PCDATA|numero)*> <!-- "|"两者选其一，*可以多次出现-->
<!ELEMENT numero (#PCDATA)>
<!ELEMENT usager (prenom,nom)>
<!ATTLIST usager id ID #REQUIRED>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

=== positive-real-function/XML/code/TD_DTD_schema/gare.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE gare SYSTEM "gare.dtd"> -->
<gare xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="gare.xsd">
<!-- <gare> -->
    <train numero="t5560" type="TGV">
        <voiture numero="v1">
            <resa numero="r17" id="u55" />
            <resa numero="r18" id="u52" />
        </voiture>
        <voiture numero="v2" />
        <voiture numero="v3" />
        <voiture numero="v4">
            <bar service="froid uniquement" />
        </voiture>
        <commentaire>Remplace lâ€™ancien TGV 
            <numero>t4215</numero>
        </commentaire>
    </train>
    <train numero="t6731">
        <voiture numero="v1" />
        <voiture numero="v2">
            <resa numero="r15" id="u55" />
        </voiture>
    </train>
    <usager id="u55">
        <prenom>Jean</prenom>
        <nom>Dufour</nom>
    </usager>
    <usager id="u52">
        <prenom>Brigitte</prenom>
        <nom>Lefebvre</nom>
    </usager>
    <usager id="u56">
        <prenom>Patrick</prenom>
        <nom>Subiran</nom>
    </usager>
</gare>
