=== positive-real-function/XML/code/TP_dtd_schema/22213816_Zhuoyuan JIN/resto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="carte" type="CarteType">

        <xsd:key name="ID_Plat">
            <xsd:selector xpath="plat"/>
            <xsd:field xpath="@ref"/>
        </xsd:key>
            
        <xsd:keyref name="ID_Composant" refer="ID_Plat">
            <xsd:selector xpath="menu/composant"/>
            <xsd:field xpath="@plat"/>
        </xsd:keyref>

    </xsd:element>


    <!-- carte -->
    <xsd:complexType name="CarteType">
        <xsd:sequence>
            <xsd:element name="plat" type="PlatType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="menu" type="MenuType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- plat -->
    <xsd:complexType name="PlatType">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="remarque" type="xsd:string" minOccurs="0"/>
            <xsd:element name="recette" type="RecetteType"/>
        </xsd:sequence>
        <xsd:attribute name="ref" type="xsd:ID" use="required"/>
        <xsd:attribute name="prix" type="xsd:decimal" use="required"/>
    </xsd:complexType>

    <!-- recette -->
    <xsd:complexType name="RecetteType" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="action" type="xsd:string"/>
            <xsd:element name="ingredient" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>

    <!-- menu -->
    <xsd:complexType name="MenuType">
        <xsd:sequence>
            <xsd:element name="prix" type="xsd:decimal"/>
            <xsd:element name="composant" type="ComposantType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="nom" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- composant -->
    <xsd:complexType name="ComposantType">
        <xsd:attribute name="plat" type="xsd:IDREF" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== positive-real-function/XML/code/TP_dtd_schema/22213816_Zhuoyuan JIN/resto.xml
<!-- This XML file does not appear to have any style information associated with it. The document
tree is shown below. -->
<!-- <carte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="resto.xsd"> -->
<!DOCTYPE carte [
    <!ELEMENT carte (plat+,menu+)>
    <!ELEMENT plat (nom,remarque?,recette)>
    <!ATTLIST plat
        ref ID #REQUIRED
        prix CDATA #REQUIRED>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT remarque (#PCDATA)>
    <!ELEMENT recette (#PCDATA|action|ingredient)*>
    <!ELEMENT action (#PCDATA)>
    <!ELEMENT ingredient (#PCDATA)>

    <!ELEMENT menu (prix,composant+)>
    <!ATTLIST menu nom CDATA #REQUIRED>
    <!ELEMENT prix (#PCDATA)>
    <!ELEMENT composant EMPTY>
    <!ATTLIST composant plat IDREF #REQUIRED>
]>


<carte>
    <plat ref="bb01" prix="9.45">
        <nom>Boeuf bourguignon</nom>
        <recette>
            <action>Trancher</action> la <ingredient>viande de boeuf</ingredient> en morceaux ... </recette>
    </plat>
    <plat ref="br01" prix="13.70">
        <nom>Bar au riz safrané</nom>
        <remarque>Sauce aux baies rouges</remarque>
        <recette>
            <action>Cuire</action> au four à 190°C le <ingredient>filet de bar</ingredient> ... </recette>
    </plat>
    <plat ref="tm01" prix="3.20">
        <nom>Tomate mozzarella</nom>
        <recette>
            <action>Couper</action> les <ingredient>tomates</ingredient> et la <ingredient>
            mozarrella</ingredient> en tranches fines ... </recette>
    </plat>
    <plat ref="cb01" prix="4.00">
        <nom>Crème brulée</nom>
        <recette>
            <action>Mélanger</action> les <ingredient>oeufs</ingredient> et le <ingredient>sucre</ingredient>
            ... </recette>
    </plat>
    <plat ref="fg01" prix="6.30">
        <nom>Foie gras</nom>
        <remarque>A la truffe</remarque>
        <recette />
    </plat>
    <menu nom="Midi">
        <prix>15.50</prix>
        <composant plat="tm01" />
        <composant plat="bb01" />
        <composant plat="cb01" />
    </menu>
    <menu nom="Gastronomique">
        <prix>21.50</prix>
        <composant plat="fg01" />
        <composant plat="br01" />
        <composant plat="cb01" />
    </menu>
</carte>
